apiVersion: v1beta1
id: nginx
kind: Pod
desiredState:
  manifest:
    version: v1beta1
    id: nginx
    containers:
      - name: nginx
        image: nginx:latest
        ports:
          - hostPort: 8091
            containerPort: 80
